name: Create Tag and GitHub Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g. 1.0.0)'
        required: true

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Tag version
        run: |
          git tag v${{ github.event.inputs.release_version }}
          git push origin v${{ github.event.inputs.release_version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.release_version }}
          name: Release v${{ github.event.inputs.release_version }}
          generate_release_notes: true
